name: 'Danger JS'
on: [pull_request_target]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.4.0
      - uses: actions/checkout@v1
      - name: Install
        run: pnpm install
      - name: Danger
        uses: danger/danger-js@10.6.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
